export const AutoIncrementCodeType = {
  EMPLOYEE: 'EMPLOYEE',
  UNIT: 'UNIT',
  RECRUITMENT_CANDIDATE: 'RECRUITMENT_CANDIDATE',
  RECRUITMENT_CAMPAIGN: 'RECRUITMENT_CAMPAIGN'
};

export const SubmissionDeadlineType = {
  EVALUATION: 'EVALUATION',
  TIMEKEEPING: 'TIMEKEEPING'
};