export const EMPLOYEE_PERMISSION = {
  VIEW: '/HRM/HRM_EMPLOYEES/HRM_EMPLOYEES-ACTIVITY/VIEW',
  CREATE: '/HRM/HRM_EMPLOYEES/HRM_EMPLOYEES-ACTIVITY/CREATE',
  UPDATE: '/HRM/HRM_EMPLOYEES/HRM_EMPLOYEES-ACTIVITY/UPDATE',
  DELETE: '/HRM/HRM_EMPLOYEES/HRM_EMPLOYEES-ACTIVITY/DELETE',
};
export const ethnics = [
  'Kinh',
  'Tày',
  'Mường',
  'Thái',
  'Khmer',
  'Nùng',
  'Hoa',
  'Dao',
  'H Mong',
  'Gia Rai',
  'Ê Đê',
  'Ba Na',
  'Sán Chay',
  'Cơ Tu',
  'Xơ Đăng',
  'Sán Dìu',
  'Chăm',
  'Ra Glai',
  'M nông',
  'Thổ',
  'Brâu',
  'Ơ Đu',
  'Khơ Mú',
  'Giáy',
  'Cờ Lao',
  'La Hủ',
  'La Chi',
  'Xinh Mun',
  'Hrê',
  'Kháng',
  'Co',
  'X tiêng',
  'Bru-Vân Kiều',
  'Cơ Lao',
  'Thái',
  'Mương',
  'Bố Y',
  'Gié Triêng',
  'Mang',
  'Chu Ru'
];
export const religions = [
  'Không',
  'Phật giáo',
  'Công giáo',
  'Tin lành',
  'Hồi giáo',
  'Ấn Độ giáo',
  'Bà-la-môn',
  'Cao Đài',
  'Hòa Hảo',
  'Đạo Bửu Sơn Kỳ Hương',
  'Đạo Tứ Ân Hiếu Nghĩa',
  'Đạo Quân Âm',
  'Đạo Trời',
  'Đạo Bửu Lâm',
  'Đạo Minh Sư',
  'Đạo Bửu Thiên',
  'Đạo Hòa Ân',
  'Đạo Hòa Hảo Bác Cổ',
  'Đạo Bửu Chánh',
  'Đạo Bửu Sơn',
  'Đạo Bửu Quang',
  'Đạo Kim Cang',
  'Đạo Tịnh Độ'
];