export interface DocumentFromInterface {
  id: string,
  excerptFromTheText: string,
  content: string,
  documentType: string,
  registrationNo: string,
  documentNo: string,
  noSaved: string,
  dateIssued: Date | string,
  toDate: Date | string,
  processingDeadline: Date | string,
  branch: string,
  documentForm: string,
  urgency: string,
  confidentiality: string,
  signer: string,
  issuingAgency: string,
  fileAttach: string,
  appendixFile: string,
  appendixFormFile: string
}

export interface DocumentToInterface {
  id: string,
  excerptFromTheText: string,
  content: string,
  documentType: string,
  registrationNo: string,
  unitGetRegistrationNumber: string,
  documentNo: string,
  noSaved: string,
  dateIssued: Date | string,
  toDate: Date | string,
  processingDeadline: Date | string,
  branch: string,
  documentForm: string,
  urgency: string,
  confidentiality: string,
  signer: string,
  issuingAgency: string,
  fileAttach: string,
  appendixFile: string,
  appendixFormFile: string,
}
